version: '3'
 
services:
  api:
    build: penguin/
    command: sh -c "cd /code/; pip install -r ./requirements.txt; python3 ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./penguin:/code
    tty: true
    ports:
      - "8000:8000"
